# Generated by Django 5.2.3 on 2025-08-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
