# Generated by Django 5.2.3 on 2025-07-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
